export const ACTIONS = {
    // films
    SET_ALL_FILM_ITEMS: 'SET_ALL_FILM_ITEMS',

    // film viewer
    SET_ACTIVE_FILM: 'SET_ACTIVE_FILM',
    SET_SEARCH_STRING: 'SET_SEARCH_STRING',
    SET_ACTIVE_GENRE: 'SET_ACTIVE_GENRE',
    SET_SORT_TYPE: 'SET_SORT_TYPE',
    SET_SORT_ORDER: 'SET_SORT_ORDER',
};